### ISSUE TITLE
[bug] 비공개 포스팅 발행 후 작성자가 포스팅 페이지 접속 불가 

### ISSUE THREAD

**Issue by SHINSOJIN** [project-555/plog-front#105]
# 발생 경위

비공개로 포스팅을 발행하고나서 작성자가 본인의 비공개 글에 접근할 수 없습니다. 

# 발생 내용

<img width="1440" alt="스크린샷 2023-10-25 오후 9 39 16" src="https://github.com/project-565/plog-back/assets/76871305/649605f9-e58f-42d7-8f77-f21ab429c480">

# 기대 결과

비공개 포스팅 페이지는 본인은 볼 수 있어야합니다.

**Comment by YangTaeyoung** [comment]
프론트 이슈이므로 해당 이슈를 프론트 레포로 이관합니다.

**Comment by SHINSOJIN** [comment]
확인했습니다. 

블로그 홈에서 포스팅 목록을 조회할 때 비공개 여부에 대한 데이터를 추가하면 좋을 것 같다는 생각입니다. 
목록이나 비공개 포스팅 상세 페이지에서도 비공개인지 아닌지를 확인할 수 없어서요
