### ISSUE TITLE
[bug]특정 카테고리를 보고있을 때 카테고리명이 포스팅 상단에 노출되지 않음

### ISSUE THREAD

**Issue by aiaaua** [project-555/plog-front#72]
# 발생 경위

블로그에 들어와 전체 카테고리의 포스팅을 홈에서 보여주다가 특정 카테고리 클릭시 해당 카테고리 글만 보이게 됨
그런데 어떤 카테고리를 보고있는지 화면에 나와있지 않아 어색하게 느껴짐

# 발생 내용

![특정 카테고리의포스트만볼때](https://github.com/project-565/plog-front/assets/55227276/4d571113-13d2-449b-86c1-aee3d026e8d5)

# 기대 결과

특정 카테고리를 보고있을 때, 혹은 전체 카테고리를 보고있을 때 카테고리명을 포스팅 상단에 노출

**Comment by YangTaeyoung** [comment]
해당 부분은 #73 에서 카테고리 글씨를 강조하는 방향으로 처리하여 해결하였습니다. 
다른 방식으로 카테고리를 쇼잉하는 것이 더 필요할까요?

**Comment by YangTaeyoung** [comment]
카테고리 메뉴 강조 처리로 처리하지 않음으로 결정하고 해당 이슈를 종료
