### ISSUE TITLE
[bug]대댓글 작성 시 띄어쓰기 안됨

### ISSUE THREAD

**Issue by aiaaua** [project-555/plog-front#79]
# 발생 경위

대댓글 작성 시 띄어쓰기가 없어짐
# 발생 내용

![대댓글띄어쓰기안됨](https://github.com/project-565/plog-front/assets/55227276/1dad7ff4-bf6c-4d19-9d48-5ddfa2c13002)

# 기대 결과

대댓글 작성 시 띄어쓰기 그대로 반영

**Comment by YangTaeyoung** [comment]
백쪽에서는 따로 문자열을 가공하지 않아서 해당 부분은 소진님께 할당하겠습니다.
