### ISSUE TITLE
[bug]간헐적으로 대댓글이 달리지 않음

### ISSUE THREAD

**Issue by aiaaua** [project-555/plog-front#80]
# 발생 경위

간헐적으로 대댓글이 달리지 않음

# 발생 내용

![간헐적으로대댓글안달림](https://github.com/project-565/plog-front/assets/55227276/c4a1e1a7-0d69-4ac8-b756-af5f2019fab9)

![image](https://github.com/project-565/plog-front/assets/55227276/1fee90d4-cceb-45ec-8b59-ac90433c8cbb)

# 기대 결과

댓글 잘 달리기

**Comment by YangTaeyoung** [comment]
현상만으로는 프론트 이슈로 보여서 소진님께 할당하겠습니다.

**Comment by SHINSOJIN** [comment]
프론트에서는 예외처리 추가하여, alert메세지를 띄우는 것으로 처리했습니다.
