### ISSUE TITLE
[bug]블로그 주인에게 다른 사람 댓글 삭제 버튼 없음

### ISSUE THREAD

**Issue by aiaaua** [project-555/plog-front#88]
# 발생 경위

포스팅 댓글 창에서 주인의 경우 타인의 댓글은 컨트롤 할 수 있는 방법이 없는게 어색하게 느껴짐

# 발생 내용

![블로그주인에게다른사람댓글삭제권한](https://github.com/project-565/plog-front/assets/55227276/20c9bbc6-65b4-411a-8075-0711ef84802c)

# 기대 결과

주인의 경우 타인의 댓글은 삭제만 할 수있게 버튼추가

**Comment by YangTaeyoung** [comment]
해당 부분은 백엔드에서는 주인, 혹은 코멘트를 남긴 사람이 삭제할 수 있도록 하고 있습니다.
타인의 댓글을 블로그 주인장이 보았을 때는 수정은 없애고 삭제 버튼만 노출시키면 좋을 듯 합니다.

해당 이슈는 백쪽 이슈에서는 수정이 불요하여 소진님께 부여하겠습니다.
